[tool.poetry]
name = "new-project"
version = "0.1.0"
description = "my new project with poetry for try"
authors = ["Yelbek"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
